name: Read hello.txt file
on:
  push:
    branches:
      - main


jobs:
read-content:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
        uses: actions/checkout@v4

    - name: Read hello.txt content
        run: cat hello.txt
      